### ISSUE TITLE
Check quick menu work well on dex and tablet

### ISSUE THREAD

**Issue by jdragonbae** [triplebanana/triple_banana#1005]
For resolving this issue, we should check quick menu 
on dex and tablet device.

**Comment by jdragonbae** [comment]
On tablet (P OS / TAB S6 / ENG), occurs the crash. Please, refer the below log.
````
01-06 18:03:15.150 16754 16754 E AndroidRuntime: Process: org.triple.banana, PID: 16754
01-06 18:03:15.150 16754 16754 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.drawable.Drawable.setCallback(android.graphics.drawable.Drawable$Callback)' on a null object reference
01-06 18:03:15.150 16754 16754 E AndroidRuntime: 	at android.graphics.drawable.LayerDrawable.<init>(LayerDrawable.java:141)
01-06 18:03:15.150 16754 16754 E AndroidRuntime: 	at android.graphics.drawable.LayerDrawable.<init>(LayerDrawable.java:119)
01-06 18:03:15.150 16754 16754 E AndroidRuntime: 	at org.triple.banana.quick_menu.QuickMenuMiddleButton.setCompoundDrawablesWithIntrinsicBounds(QuickMenuMiddleButton.java:49)
01-06 18:03:15.150 16754 16754 E AndroidRuntime: 	at android.widget.TextView.<init>(TextView.java:1764)
01-06 18:03:15.150 16754 16754 E AndroidRuntime: 	at android.widget.Button.<init>(Button.java:181)
01-06 18:03:15.150 16754 16754 E AndroidRuntime: 	at android.widget.Button.<init>(Button.java:156)
01-06 18:03:15.150 16754 16754 E AndroidRuntime: 	at androidx.appcompat.widget.AppCompatButton.<init>(AppCompatButton.java:74)
01-06 18:03:15.150 16754 16754 E AndroidRuntime: 	at androidx.appcompat.widget.AppCompatButton.<init>(AppCompatButton.java:69)
01-06 18:03:15.150 16754 16754 E AndroidRuntime: 	at org.triple.banana.quick_menu.QuickMenuMiddleButton.<init>(QuickMenuMiddleButton.java:29)
01-06 18:03:15.150 16754 16754 E AndroidRuntime: 	at org.triple.banana.quick_menu.QuickMenuMiddleButton.<init>(QuickMenuMiddleButton.java:25)
01-06 18:03:15.150 16754 16754 E AndroidRuntime: 	at org.triple.banana.quick_menu.QuickMenuDialog.updateButtons(QuickMenuDialog.java:74)
01-06 18:03:15.150 16754 16754 E AndroidRuntime: 	at org.triple.banana.quick_menu.QuickMenuDialog.show(QuickMenuDialog.java:118)
01-06 18:03:15.150 16754 16754 E AndroidRuntime: 	at org.triple.banana.quick_menu.QuickMenuViewImpl.onUpdate(QuickMenuViewImpl.java:26)
01-06 18:03:15.150 16754 16754 E AndroidRuntime: 	at org.triple.banana.quick_menu.QuickMenuFactoryImpl$$Lambda$2.onUpdate(Unknown Source:4)
01-06 18:03:15.150 16754 16754 E AndroidRuntime: 	at org.triple.banana.base.model.Model.commit(Model.java:84)
01-06 18:03:15.150 16754 16754 E AndroidRuntime: 	at org.triple.banana.quick_menu.QuickMenuControllerImpl.show(QuickMenuControllerImpl.java:38)
01-06 18:03:15.150 16754 16754 E AndroidRuntime: 	at org.triple.banana.toolbar.ButtonId.lambda$static$5$ButtonId(ButtonId.java:69)
01-06 18:03:15.150 16754 16754 E AndroidRuntime: 	at org.triple.banana.toolbar.ButtonId$$Lambda$6.onClick(Unknown Source:0)
01-06 18:03:15.150 16754 16754 E AndroidRuntime: 	at android.view.View.performClick(View.java:7368)
01-06 18:03:15.150 16754 16754 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:7334)
01-06 18:03:15.150 16754 16754 E AndroidRuntime: 	at android.view.View.access$3200(View.java:849)
01-06 18:03:15.150 16754 16754 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:27906)
01-06 18:03:15.150 16754 16754 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
01-06 18:03:15.150 16754 16754 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-06 18:03:15.150 16754 16754 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:216)
01-06 18:03:15.150 16754 16754 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7285)
01-06 18:03:15.150 16754 16754 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-06 18:03:15.150 16754 16754 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
01-06 18:03:15.150 16754 16754 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
````

**Comment by jdragonbae** [comment]
On dex mode ( Q OS / S 20 / ENG ), the quick menu seems to be work well.
