### ISSUE TITLE
A crash occur in debug build

### ISSUE THREAD

**Issue by romandev** [triplebanana/triple_banana#1139]
```
04-03 02:48:24.619 14771 14771 D AndroidRuntime: Shutting down VM
04-03 02:48:24.620 14771 14771 E AndroidRuntime: FATAL EXCEPTION: main
04-03 02:48:24.620 14771 14771 E AndroidRuntime: Process: org.triple.banana_beta, PID: 14771
04-03 02:48:24.620 14771 14771 E AndroidRuntime: java.lang.ExceptionInInitializerError
04-03 02:48:24.620 14771 14771 E AndroidRuntime:        at org.chromium.chrome.browser.base.SplitCompatApplication.attachBaseContext(SplitCompatApplication.java:160)
04-03 02:48:24.620 14771 14771 E AndroidRuntime:        at org.banana.cake.bootstrap.BananaApplication.attachBaseContext(BananaApplication.java:22)
04-03 02:48:24.620 14771 14771 E AndroidRuntime:        at android.app.Application.attach(Application.java:370)
04-03 02:48:24.620 14771 14771 E AndroidRuntime:        at android.app.Instrumentation.newApplication(Instrumentation.java:1157)
04-03 02:48:24.620 14771 14771 E AndroidRuntime:        at android.app.LoadedApk.makeApplication(LoadedApk.java:1288)
04-03 02:48:24.620 14771 14771 E AndroidRuntime:        at android.app.ActivityThread.handleMakeApplication(ActivityThread.java:7152)
04-03 02:48:24.620 14771 14771 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7134)
04-03 02:48:24.620 14771 14771 E AndroidRuntime:        at android.app.ActivityThread.access$1600(ActivityThread.java:274)
04-03 02:48:24.620 14771 14771 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2102)
04-03 02:48:24.620 14771 14771 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:107)
04-03 02:48:24.620 14771 14771 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:237)
04-03 02:48:24.620 14771 14771 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8167)
04-03 02:48:24.620 14771 14771 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
04-03 02:48:24.620 14771 14771 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
04-03 02:48:24.620 14771 14771 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
04-03 02:48:24.620 14771 14771 E AndroidRuntime: Caused by: java.lang.RuntimeException: java.lang.IllegalAccessException: java.lang.Class<org.triple.banana.cake_api.CakeApiImpl> is not accessible from java.lang.Class<org.chromium.components.module_installer.builder.Module>
04-03 02:48:24.620 14771 14771 E AndroidRuntime:        at org.chromium.components.module_installer.builder.Module.instantiateReflectively(Module.java:203)
04-03 02:48:24.620 14771 14771 E AndroidRuntime:        at org.chromium.components.module_installer.builder.Module.getImpl(Module.java:112)
04-03 02:48:24.620 14771 14771 E AndroidRuntime:        at org.triple.banana.cake_api.CakeApiModule.getImpl(CakeApiModule.java:30)
04-03 02:48:24.620 14771 14771 E AndroidRuntime:        at banana.cake.<clinit>(cake.java:12)
04-03 02:48:24.620 14771 14771 E AndroidRuntime:        ... 15 more
04-03 02:48:24.620 14771 14771 E AndroidRuntime: Caused by: java.lang.IllegalAccessException: java.lang.Class<org.triple.banana.cake_api.CakeApiImpl> is not accessible from java.lang.Class<org.chromium.components.module_installer.builder.Module>
04-03 02:48:24.620 14771 14771 E AndroidRuntime:        at java.lang.Class.newInstance(Native Method)
04-03 02:48:24.620 14771 14771 E AndroidRuntime:        at org.chromium.components.module_installer.builder.Module.instantiateReflectively(Module.java:201)
04-03 02:48:24.620 14771 14771 E AndroidRuntime:        ... 18 more
```

**Comment by romandev** [comment]
```
04-03 17:28:47.593 32004 32004 E AndroidRuntime: java.lang.RuntimeException: Unable to resume activity {org.triple.banana_beta/com.google.android.apps.chrome.Main}: java.lang.ClassCastException: org.chromium.chrome.browser.tabmodel.EmptyTabModelFilter cannot be cast to org.chromium.chrome.browser.tasks.tab_groups.TabGroupModelFilter
04-03 17:28:47.593 32004 32004 E AndroidRuntime:        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4657)
04-03 17:28:47.593 32004 32004 E AndroidRuntime:        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4690)
04-03 17:28:47.593 32004 32004 E AndroidRuntime:        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
04-03 17:28:47.593 32004 32004 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
04-03 17:28:47.593 32004 32004 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
04-03 17:28:47.593 32004 32004 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
04-03 17:28:47.593 32004 32004 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:107)
04-03 17:28:47.593 32004 32004 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:237)
04-03 17:28:47.593 32004 32004 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8167)
04-03 17:28:47.593 32004 32004 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
04-03 17:28:47.593 32004 32004 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
04-03 17:28:47.593 32004 32004 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
04-03 17:28:47.593 32004 32004 E AndroidRuntime: Caused by: java.lang.ClassCastException: org.chromium.chrome.browser.tabmodel.EmptyTabModelFilter cannot be cast to org.chromium.chrome.browser.tasks.tab_groups.TabGroupModelFilter
04-03 17:28:47.593 32004 32004 E AndroidRuntime:        at org.chromium.chrome.browser.tasks.tab_management.TabGroupUiCoordinator.recordTabGroupCount(TabGroupUiCoordinator.java:253)
04-03 17:28:47.593 32004 32004 E AndroidRuntime:        at org.chromium.chrome.browser.tasks.tab_management.TabGroupUiCoordinator.onResumeWithNative(TabGroupUiCoordinator.java:230)
04-03 17:28:47.593 32004 32004 E AndroidRuntime:        at org.chromium.chrome.browser.init.ActivityLifecycleDispatcherImpl.dispatchOnResumeWithNative(ActivityLifecycleDispatcherImpl.java:157)
04-03 17:28:47.593 32004 32004 E AndroidRuntime:        at org.chromium.chrome.browser.init.AsyncInitializationActivity.onResumeWithNative(AsyncInitializationActivity.java:543)
04-03 17:28:47.593 32004 32004 E AndroidRuntime:        at org.chromium.chrome.browser.app.ChromeActivity.onResumeWithNative(ChromeActivity.java:943)
04-03 17:28:47.593 32004 32004 E AndroidRuntime:        at org.chromium.chrome.browser.ChromeTabbedActivity.onResumeWithNative(ChromeTabbedActivity.java:849)
04-03 17:28:47.593 32004 32004 E AndroidRuntime:        at org.chromium.chrome.browser.init.NativeInitializationController.onResume(NativeInitializationController.java:166)
04-03 17:28:47.593 32004 32004 E AndroidRuntime:        at org.chromium.chrome.browser.init.AsyncInitializationActivity.onResume(AsyncInitializationActivity.java:493)
04-03 17:28:47.593 32004 32004 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1454)
04-03 17:28:47.593 32004 32004 E AndroidRuntime:        at android.app.Activity.performResume(Activity.java:8111)
04-03 17:28:47.593 32004 32004 E AndroidRuntime:        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4647)
```

**Comment by romandev** [comment]
Another class is present..
