### ISSUE TITLE
A crash occurs on MediaRemote

### ISSUE THREAD

**Issue by romandev** [triplebanana/triple_banana#741]
**Reproducible steps**
1. Run Banana Browser
2. Play YouTube on MediaRemote
3. Home button (N-OS)
4. Remove the Banana Browser from recent app list
5. Re-run Banana Browser

```
09-23 01:17:57.869 14051 14051 W System.err: java.lang.IllegalArgumentException: View=DecorView@454939a[ChromeTabbedActivity] not attached to window manager
09-23 01:17:57.873 14051 14051 W System.err:    at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:479)
09-23 01:17:57.873 14051 14051 W System.err:    at android.view.WindowManagerGlobal.updateViewLayout(WindowManagerGlobal.java:374)
09-23 01:17:57.873 14051 14051 W System.err:    at android.view.WindowManagerImpl.updateViewLayout(WindowManagerImpl.java:103)
09-23 01:17:57.873 14051 14051 W System.err:    at android.app.Dialog.onWindowAttributesChanged(Dialog.java:970)
09-23 01:17:57.873 14051 14051 W System.err:    at android.view.Window.dispatchWindowAttributesChanged(Window.java:1109)
09-23 01:17:57.873 14051 14051 W System.err:    at com.android.internal.policy.PhoneWindow.dispatchWindowAttributesChanged(PhoneWindow.java:3211)
09-23 01:17:57.873 14051 14051 W System.err:    at android.view.Window.setAttributes(Window.java:1140)
09-23 01:17:57.873 14051 14051 W System.err:    at com.android.internal.policy.PhoneWindow.setAttributes(PhoneWindow.java:4100)
09-23 01:17:57.874 14051 14051 W System.err:    at org.triple.banana.util.BrightnessUtil.setWindowBrightness(BrightnessUtil.java:47)
09-23 01:17:57.874 14051 14051 W System.err:    at org.triple.banana.media_remote.MediaRemoteViewImpl.updateBrightness(MediaRemoteViewImpl.java:274)
09-23 01:17:57.874 14051 14051 W System.err:    at org.triple.banana.media_remote.MediaRemoteViewImpl.onUpdate(MediaRemoteViewImpl.java:260)
09-23 01:17:57.874 14051 14051 W System.err:    at org.triple.banana.media_remote.MediaRemoteViewModel.commit(MediaRemoteViewModel.java:168)
09-23 01:17:57.874 14051 14051 W System.err:    at org.triple.banana.media_remote.MediaRemoteService$1.onPlayStateChanged(MediaRemoteService.java:64)
09-23 01:17:57.874 14051 14051 W System.err:    at org.triple.banana.media.MediaEventDispatcher.onPlayStateChanged(MediaEventDispatcher.java:49)
09-23 01:17:57.874 14051 14051 W System.err:    at org.triple.banana.media.mojom.BananaMediaEventDispatcher_Internal$Stub.accept(BananaMediaEventDispatcher_Internal.java:190)
09-23 01:17:57.874 14051 14051 W System.err:    at org.chromium.mojo.bindings.RouterImpl.handleIncomingMessage(RouterImpl.java:238)
09-23 01:17:57.874 14051 14051 W System.err:    at org.chromium.mojo.bindings.RouterImpl.access$000(RouterImpl.java:21)
09-23 01:17:57.874 14051 14051 W System.err:    at org.chromium.mojo.bindings.RouterImpl$HandleIncomingMessageThunk.accept(RouterImpl.java:33)
09-23 01:17:57.875 14051 14051 W System.err:    at org.chromium.mojo.bindings.Connector.readAndDispatchMessage(Connector.java:210)
09-23 01:17:57.875 14051 14051 W System.err:    at org.chromium.mojo.bindings.Connector.readOutstandingMessages(Connector.java:176)
09-23 01:17:57.875 14051 14051 W System.err:    at org.chromium.mojo.bindings.Connector.onWatcherResult(Connector.java:152)
09-23 01:17:57.875 14051 14051 W System.err:    at org.chromium.mojo.bindings.Connector.access$100(Connector.java:25)
09-23 01:17:57.875 14051 14051 W System.err:    at org.chromium.mojo.bindings.Connector$WatcherCallback.onResult(Connector.java:142)
09-23 01:17:57.875 14051 14051 W System.err:    at org.chromium.mojo.system.impl.WatcherImpl.onHandleReady(WatcherImpl.java:56)
09-23 01:17:57.875 14051 14051 W System.err:    at android.os.MessageQueue.nativePollOnce(Native Method)
09-23 01:17:57.875 14051 14051 W System.err:    at android.os.MessageQueue.next(MessageQueue.java:323)
09-23 01:17:57.876 14051 14051 W System.err:    at android.os.Looper.loop(Looper.java:136)
09-23 01:17:57.876 14051 14051 W System.err:    at android.app.ActivityThread.main(ActivityThread.java:6682)
09-23 01:17:57.876 14051 14051 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
09-23 01:17:57.876 14051 14051 W System.err:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
09-23 01:17:57.876 14051 14051 W System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
09-23 01:18:00.644 18060 18060 F DEBUG   :     #37 pc 00000000000a7728  /system/lib64/libandroid_runtime.so (_ZN7android14AndroidRuntime5startEPKcRKNS_6VectorINS_7String8EEEb+712)
```

**Comment by romandev** [comment]
Fixed by #752
