### ISSUE TITLE
A crash occurs in 32bit apk

### ISSUE THREAD

**Issue by romandev** [triplebanana/triple_banana#846]
```
11-08 22:23:28.880  8913  8913 W System.err: java.lang.UnsatisfiedLinkError: No implementation found for java.lang.String org.chromium.base.natives.GEN_JNI.org_banana_cake_CakeSubresourceFilter_getVersion() (tried Java_org_chromium_base_natives_GEN_1JNI_org_1banana_1cake_1CakeSubresourceFilter_1getVersion and Java_org_chromium_base_natives_GEN_1JNI_org_1banana_1cake_1CakeSubresourceFilter_1getVersion__)
11-08 22:23:28.881  8913  8913 W System.err:    at org.chromium.base.natives.GEN_JNI.org_banana_cake_CakeSubresourceFilter_getVersion(Native Method)
11-08 22:23:28.881  8913  8913 W System.err:    at org.banana.cake.CakeSubresourceFilterJni.getVersion(CakeSubresourceFilterJni.java:39)
11-08 22:23:28.881  8913  8913 W System.err:    at org.banana.cake.CakeSubresourceFilter.getVersion(CakeSubresourceFilter.java:27)
11-08 22:23:28.881  8913  8913 W System.err:    at org.triple.banana.subresource_filter.RulesetLoader.getVersion(RulesetLoader.java:220)
11-08 22:23:28.881  8913  8913 W System.err:    at org.triple.banana.subresource_filter.RulesetLoader.updateBuiltInRuleset(RulesetLoader.java:93)
11-08 22:23:28.881  8913  8913 W System.err:    at org.triple.banana.subresource_filter.RulesetLoader.updateRulesetIfNeeded(RulesetLoader.java:248)
11-08 22:23:28.881  8913  8913 W System.err:    at org.triple.banana.TripleBananaApplication.onInitialized(TripleBananaApplication.java:78)
11-08 22:23:28.881  8913  8913 W System.err:    at org.banana.cake.bootstrap.BananaApplication.lambda$attachBaseContext$0$BananaApplication(BananaApplication.java:24)
11-08 22:23:28.881  8913  8913 W System.err:    at org.banana.cake.bootstrap.BananaApplication$$Lambda$0.run(Unknown Source:2)
11-08 22:23:28.881  8913  8913 W System.err:    at org.chromium.chrome.browser.init.ChromeBrowserInitializer.onFinishFullBrowserInitialization(ChromeBrowserInitializer.java:397)
11-08 22:23:28.882  8913  8913 W System.err:    at org.chromium.chrome.browser.init.ChromeBrowserInitializer.bridge$lambda$1$ChromeBrowserInitializer(Unknown Source:0)
11-08 22:23:28.882  8913  8913 W System.err:    at org.chromium.chrome.browser.init.ChromeBrowserInitializer$$Lambda$9.run(Unknown Source:2)
11-08 22:23:28.882  8913  8913 W System.err:    at org.chromium.chrome.browser.init.ChainedTasks$1.run(ChainedTasks.java:33)
11-08 22:23:28.882  8913  8913 W System.err:    at android.os.MessageQueue.nativePollOnce(Native Method)
11-08 22:23:28.882  8913  8913 W System.err:    at android.os.MessageQueue.next(MessageQueue.java:336)
11-08 22:23:28.882  8913  8913 W System.err:    at android.os.Looper.loop(Looper.java:197)
11-08 22:23:28.882  8913  8913 W System.err:    at android.app.ActivityThread.main(ActivityThread.java:8016)
11-08 22:23:28.882  8913  8913 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
11-08 22:23:28.882  8913  8913 W System.err:    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
11-08 22:23:28.882  8913  8913 W System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
11-08 22:23:28.926  8913  8913 F chromium: [FATAL:jni_android.cc(249)] Please include Java exception stack in crash report
11-08 22:23:30.181  9106  9106 F DEBUG   : Abort message: '[FATAL:jni_android.cc(249)] Please include Java exception stack in crash report'
11-08 22:23:30.579  9106  9106 F DEBUG   :       #65 pc 000a7319  /system/lib/libandroid_runtime.so (android::AndroidRuntime::start(char const*, android::Vector<android::String8> const&, bool)+508) (BuildId: 2f7d6b0aa81ca19a463c650d9bdd393f)
```

**Comment by romandev** [comment]
This is still reproducible on L-OS. We need more checks in other OS versions.
